glutInit()
glutInitDisplayMode(GLUT_RGBA | GLUT_DOUBLE)
glutInitWindowSize(WIDTH, HEIGHT)
glutCreateWindow(b"Jumping Car Adventure")
glOrtho(0, WIDTH, 0, HEIGHT, -1, 1)
glClearColor(0, 0, 0, 1)
glutIdleFunc(animation)
glutKeyboardFunc(keyboard)
glutDisplayFunc(display)
glutMainLoop()