car_transition_width_corrector_ = 30
car_transition_height_corrector_ = 0
screen_width_ , screen_height_ = 850 , 550
gravels_ = []
start_game_ = True
car_velo_y_ = 0
car_jump_upward_ = False
tree_speed_game_ = 5
score_game_ = 0
start_right_game = 755
start_left_ = 745
illusion_game_ = True
cloud_shifting_r_ = False
shifting_magnitude_ = 0
